name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # 🔑 Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Start your dev server if needed
      - name: Start server
        run: npm start &

      - name: Wait for server
        run: sleep 5

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test --reporter=list

      # 📦 Upload Playwright artifacts kung may failure
      - name: Upload Playwright Artifacts
        if: failure() # Tatakbo lang kapag may failed tests
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            playwright-report
            test-results
        
      # 🚀 Simulated deploy step
      - name: Simulated Deploy
        if: success()
        run: |
          echo "--------------------------------------"
          echo "🚀 Simulated deployment successful!"
          echo "App would be deployed here in a real setup."
          echo "--------------------------------------"

